version: "3.9"
services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes: 
      - .:/app
      - ./app/data:/app/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
